
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import *
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from powerbase import *
from base import *
from power import *


class Ui_calculus(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 314)
        #MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 85))
        #self.pushButton_2.setIcon(QIcon("image : url(cal1.png);"))
        self.pushButton.setStyleSheet("background-color:white;\n"
        "image : url(cal1.png);")
        self.pushButton.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setStyleSheet("background-color:white;\n"
        "image : url(cal2.png);")
        self.pushButton_2.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setStyleSheet("background-color:white;\n"
        "image : url(cal3.png);")
        self.pushButton_3.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setStyleSheet("background-color:white;\n"
        "image : url(cal4.png);")
        self.pushButton_4.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setStyleSheet("background-color:white;\n"
        "image : url(cal5.png);")
        self.pushButton_5.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_5, 1, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setStyleSheet("background-color:white;\n"
        "image : url(cal6.png);")
        self.pushButton_6.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_6, 1, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setStyleSheet("background-color:white;\n"
        "image : url(cal7.png);")
        self.pushButton_7.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_7, 1, 6, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setStyleSheet("background-color:white;\n"
        "image : url(cal8.png);")
        self.pushButton_8.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_8, 1, 7, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setStyleSheet("background-color:white;\n"
        "image : url(cal9.png);")
        self.pushButton_9.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_9, 1, 8, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setStyleSheet("background-color:white;\n"
        "image : url(cal10.png);")
        self.pushButton_10.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setStyleSheet("background-color:white;\n"
        "image : url(cal11.png);")
        self.pushButton_11.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setStyleSheet("background-color:white;\n"
        "image : url(cal12.png);")
        self.pushButton_12.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setStyleSheet("background-color:white;\n"
        "image : url(cal13.png);")
        self.pushButton_14.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_14, 2, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_15.setStyleSheet("background-color:white;\n"
        "image : url(cal14.png);")
        self.pushButton_15.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_15, 2, 4, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_16.setStyleSheet("background-color:white;\n"
        "image : url(cal15.png);")
        self.pushButton_16.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_16, 2, 5, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_17.setStyleSheet("background-color:white;\n"
        "image : url(cal16.png);")
        self.pushButton_17.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_17, 2, 6, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_18.setStyleSheet("background-color:white;\n"
        "image : url(cal18.png);")
        self.pushButton_18.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_18, 2, 7, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_19.setStyleSheet("background-color:white;\n"
        "image : url(cal19.png);")
        self.pushButton_19.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_19, 2, 8, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_20.setStyleSheet("background-color:white;\n"
        "image : url(cal20.png);")
        self.pushButton_20.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_20, 3, 0, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton21.sizePolicy().hasHeightForWidth())
        self.pushButton21.setSizePolicy(sizePolicy)
        self.pushButton21.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton21.setStyleSheet("background-color:white;\n"
        "image : url(cal21.png);")
        self.pushButton21.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton21, 3, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_22.setStyleSheet("background-color:white;\n"
        "image : url(cal22.png);")
        self.pushButton_22.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_22, 3, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_23.setStyleSheet("background-color:white;\n"
        "image : url(cal23.png);")
        self.pushButton_23.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_23, 3, 3, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_24.setStyleSheet("background-color:white;\n"
        "image : url(cal24.png);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 3, 4, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_26.setStyleSheet("background-color:white;\n"
        "image : url(cal25.png);")
        self.pushButton_26.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_26, 3, 5, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_27.setStyleSheet("background-color:white;\n"
        "image : url(cal26.png);")
        self.pushButton_27.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_27, 3, 6, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_28.setStyleSheet("background-color:white;\n"
        "image : url(cal27.png);")
        self.pushButton_28.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_28, 3, 7, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        self.pushButton_29.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_29.setStyleSheet("background-color:white;\n"
        "image : url(cal28.png);")
        self.pushButton_29.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_29, 3, 8, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_30.setStyleSheet("background-color:white;\n"
        "image : url(cal29.png);")
        self.pushButton_30.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_30, 4, 0, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_31.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_31.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_31, 4, 1, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_32.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_32.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_32, 4, 2, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        self.pushButton_34.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_34.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_34.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_34, 4, 3 , 1, 1)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        self.pushButton_36.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_36.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_36.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_36, 4, 4, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        self.pushButton_37.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_37.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_37.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_37, 4, 5, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        self.pushButton_38.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_38.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_38.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_38, 4, 6, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        self.pushButton_39.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_39.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_39.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_39, 4, 7, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_40.sizePolicy().hasHeightForWidth())
        self.pushButton_40.setSizePolicy(sizePolicy)
        self.pushButton_40.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_40.setStyleSheet("background-color:white;\n"
        "font-size: 20px;")
        self.pushButton_40.setObjectName("pushButton_36")
        self.gridLayout.addWidget(self.pushButton_40, 4, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def powba(self):
        self.window = QMainWindow()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def power(self):
        self.window = QMainWindow()
        self.ui = Ui_power()
        self.ui.setupUi(self.window)
        self.window.show()

    def base(self):
        self.window = QMainWindow()
        self.ui = Ui_base()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculus Panel"))
        MainWindow.setWindowIcon(QIcon("Splashlogo.png"))

        self.pushButton_31.setText(_translate("MainWindow", "ε"))
        self.pushButton_32.setText(_translate("MainWindow", "δ"))
        self.pushButton_34.setText(_translate("MainWindow", "∞"))
        self.pushButton_36.setText(_translate("MainWindow", "∇"))
        self.pushButton_37.setText(_translate("MainWindow", "∂"))
        self.pushButton_38.setText(_translate("MainWindow", "ω"))
        self.pushButton_39.setText(_translate("MainWindow", "θ"))
        self.pushButton_40.setText(_translate("MainWindow", "→"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_calculus()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
